<?php
/* Author: Tomáš Bezděk */

$labels = array();
$labels['sauserprefs'] = 'Nevyžádaná pošta';
$labels['managespam'] = 'Spravovat nastavení detekce spamu';
$labels['sauserprefssettings'] = 'Nastavení pro nevyžádanou poštu';
$labels['spamgeneralsettings'] = 'Nastavení';
$labels['spamthres'] = 'Rozhodovací úroveň skóre';
$labels['spamsubject'] = 'Označení předmětu';
$labels['spamlang'] = 'Jazyky zprávy';
$labels['enabled'] = 'Povoleno';
$labels['disabled'] = 'Zakázáno';
$labels['headers'] = 'Hlavičky zpráv';
$labels['foldheaders'] = 'Povolit více řádků v hlavičkách';
$labels['spamlevelstars'] = 'Pouzít \'Spam Level\' hlavičku';
$labels['spamlevelchar'] = 'Charakter úrovně spamu';
$labels['spamtests'] = 'Internetové testy spamu';
$labels['userazor1'] = 'Použít Razor v1';
$labels['userazor2'] = 'Použít Razor v2';
$labels['usepyzor'] = 'Použít Pyzor';
$labels['usebayes'] = 'Použít Bayesiánský klasifikátor';
$labels['usedcc'] = 'Použít DCC';
$labels['skiprblchecks'] = 'Použít Realtime Blackhole list';
$labels['spamreportsettings'] = 'Oznámit nastavení';
$labels['spamreport0'] = 'Zahrnout oznámení do hlavičky originální zprávy';
$labels['spamreport1'] = 'Zahrnout originál jako MIME přílohu k oznámení';
$labels['spamreport2'] = 'Zahrnout originál jako textovou přílohu k oznámení';
$labels['spamaddressrules'] = 'Pravidla adres';
$labels['whitelist_from'] = 'Příjmout zprávu od';
$labels['blacklist_from'] = 'Odmítnouz zprávu od';
$labels['whitelist_to'] = 'Povolit odeslání příjemci';
$labels['addrule'] = 'Přidat pravidlo';
$labels['rule'] = 'Pravidlo';
$labels['importfromaddressbook'] = 'Importovat adresy z adresáře';
$labels['deleteall'] = 'Odstranit vše';
$labels['autoscore'] = 'Automaticky';
$labels['defaultscore'] = 'Výchozí hodnocení';
$labels['otherscore'] = 'Ostatní (%s)';
$labels['usedefault'] = 'Obnovit vzchozí nastavení';
$labels['langoptions'] = 'Jazyková nastavení';
$labels['bayes'] = 'Nastaveni Bayes filtru';
$labels['purgingbayes'] = 'Odstraňuji Bayesiánské data';
$labels['purgebayes'] = 'Odstranit osobní Bayesiánské data';
$labels['bayesautolearn'] = 'Použít automatické učení Bayesiánského filtru';
$labels['bayesautooptions'] = 'Nastavení automatického učení';
$labels['bayesnonspam'] = 'Úroveň vyhodnocení jako non-spam';
$labels['bayesspam'] = 'Úroveň vyhodnocení jako spam';
$labels['bayesrules'] = 'Použít Bayesiánská pravidla';
$labels['help'] = 'Nápověda';

$messages = array();

?>